### ISSUE TITLE
Docker MongoDB

### ISSUE THREAD

**Issue by hinrek** [rakenduste-programmeerimine-2017s/Raamat#1]
kui juba kasutame dockerit siis v6iks kaaluda MongoDB jooksutada ka dockeri abil
https://hub.docker.com/_/mongo/

**Comment by romilrobtsenkov** [comment]
@hinrek igal juhul. MongoDB, Node, nginx ... kõik paneb sealt tööle. Panen kohe varsti üles alusrepo Docker'i ja docker-compose'iga.
